name: household_buddy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^9.0.0
  permission_handler: ^11.3.1
  appwrite: ^14.0.0
  provider: ^6.1.2
  lottie: ^3.3.1
  email_validator: ^3.0.0
  file_picker: ^8.3.0
  google_fonts: ^6.2.1
  hexcolor: ^3.0.1
  persistent_bottom_nav_bar: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3 

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/Images/